#!/usr/bin/env python3
"""
build_site.py: Parses manifest.json from Google Drive and prepares site data for GitHub Pages.
Generates data.js so index.html loads instantly without any CORS or external API latency.
"""

import json
import re
from pathlib import Path

MANIFEST_FILE = Path("/home/h4rman/fr03-vault/manifest.json")
OUTPUT_DATA_FILE = Path("/home/h4rman/fr03-vault/data.js")

def parse_subject(path: str) -> str:
    path_lower = path.lower()
    if "recordings" in path_lower:
        return "recording"
    if "notes/physics" in path_lower:
        return "physics"
    if "notes/chemistry" in path_lower:
        return "chemistry"
    if "notes/maths" in path_lower:
        return "maths"
    return "other"

def clean_title(name: str) -> str:
    title = name
    if title.lower().endswith(".pdf"):
        title = title[:-4]
    if title.lower().startswith("fr03 "):
        title = title[5:]
    return title.strip()

def format_size(bytes_num: int) -> str:
    mb = bytes_num / (1024 * 1024)
    if mb < 1.0:
        return f"{bytes_num // 1024} kb"
    return f"{mb:.1f} mb"

def format_date(iso_str: str) -> str:
    if not iso_str:
        return "----"
    return iso_str[:10]

def main():
    if not MANIFEST_FILE.exists():
        print("error: manifest.json not found")
        return

    with open(MANIFEST_FILE, "r", encoding="utf-8") as f:
        items = json.load(f)

    entries = []
    for item in items:
        if item.get("IsDir", False):
            continue

        path = item.get("Path", "")
        name = item.get("Name", "")
        item_id = item.get("ID", "")
        size = item.get("Size", 0)
        mod_time = item.get("ModTime", "")

        # Skip raw heic images or temp artifacts
        if name.startswith(".") or name.lower().endswith(".heic"):
            continue

        subject = parse_subject(path)
        title = clean_title(name)

        entries.append({
            "title": title,
            "rawName": name,
            "subject": subject,
            "path": path,
            "size": format_size(size),
            "sizeBytes": size,
            "date": format_date(mod_time),
            "url": f"https://drive.google.com/file/d/{item_id}/view"
        })

    # Include lecture recordings discovered from email
    mail_rec_file = Path(__file__).parent / "mail_recordings.json"
    if mail_rec_file.exists():
        try:
            with open(mail_rec_file, "r", encoding="utf-8") as f:
                mail_recs = json.load(f)
            for r in mail_recs:
                if not r.get("url"):
                    continue
                d = r.get("date", "").replace("/", "-")[:10]
                entries.append({
                    "title": r.get("title", ""),
                    "rawName": r.get("title", ""),
                    "subject": "recording",
                    "path": f"recordings/{r.get('sub_category', 'general')}",
                    "size": "stream",
                    "sizeBytes": 0,
                    "date": d,
                    "url": r.get("url")
                })
        except Exception as e:
            print(f"warning: error reading mail_recordings.json: {e}")

    # Sort newest first
    entries.sort(key=lambda x: (x["date"], x["title"]), reverse=True)

    with open(OUTPUT_DATA_FILE, "w", encoding="utf-8") as f:
        f.write("// generated by build_site.py\n")
        f.write("window.VAULT_DATA = ")
        json.dump(entries, f, indent=2)
        f.write(";\n")

    print(f"generated {len(entries)} entries in data.js")

if __name__ == "__main__":
    main()
