// generated by build_site.py
window.VAULT_DATA = [
  {
    "title": "Mathematics \u00b7 Lecture-6",
    "rawName": "Mathematics \u00b7 Lecture-6",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "Thu, 10 Se",
    "url": "https://drive.google.com/file/d/16IHjLVbedGJpoMzFNpdN6DzLayGd3uf9/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-5",
    "rawName": "Mathematics \u00b7 Lecture-5",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "Thu, 10 Se",
    "url": "https://drive.google.com/file/d/1abDOgJNFLYCzLfe905NIMZZCbCq95mOk/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-1",
    "rawName": "Mathematics \u00b7 Lecture-1",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "Thu, 10 Se",
    "url": "https://drive.google.com/file/d/1YWx3KkaS1vTHAkFLGUaxSsbO1uuzLKUL/view"
  },
  {
    "title": "Straight Lines FR03",
    "rawName": "Straight Lines FR03.pdf",
    "subject": "maths",
    "path": "notes/maths/Straight Lines FR03.pdf",
    "size": "17.8 mb",
    "sizeBytes": 18690667,
    "date": "2026-10-09",
    "url": "https://drive.google.com/file/d/1kok7FZSgflQtxFAz9cUGBJePoMHBetxH/view"
  },
  {
    "title": "Mechanical Properties of Solids",
    "rawName": "FR03 Mechanical Properties of Solids.pdf",
    "subject": "physics",
    "path": "notes/physics/Mechanical Properties of Solids/FR03 Mechanical Properties of Solids.pdf",
    "size": "40.4 mb",
    "sizeBytes": 42414154,
    "date": "2026-10-09",
    "url": "https://drive.google.com/file/d/1F-HzKcKChktHiSQX6AdTePDBHUtXcm-r/view"
  },
  {
    "title": "Mechanical Properties of Fluids",
    "rawName": "FR03 Mechanical Properties of Fluids.pdf",
    "subject": "physics",
    "path": "notes/physics/Mechanical Properties of Fluids/FR03 Mechanical Properties of Fluids.pdf",
    "size": "18.7 mb",
    "sizeBytes": 19612898,
    "date": "2026-10-08",
    "url": "https://drive.google.com/file/d/1u5isa_5IP5J01GBIKnoBqKXtKyJ3-0C0/view"
  },
  {
    "title": "Step-3 Discussion",
    "rawName": "Step-3 Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Work, Energy and Power/Step-3 Discussion.pdf",
    "size": "16.4 mb",
    "sizeBytes": 17169866,
    "date": "2026-10-04",
    "url": "https://drive.google.com/file/d/1wdN6MgP8Nz5QTWdJCZVO4E9stXSd8jLy/view"
  },
  {
    "title": "Step-3 Discussion",
    "rawName": "Step-3 Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/System of Particles and Rotational Motion/Step-3 Discussion.pdf",
    "size": "170 kb",
    "sizeBytes": 174752,
    "date": "2026-10-04",
    "url": "https://drive.google.com/file/d/1OA6nc8O9Hj9LEF_-X-WQjDx1dJ3NEVNj/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-9 - 2026/10/03 12:15 IST",
    "rawName": "Mathematics \u00b7 Lecture-9 - 2026/10/03 12:15 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-10-03",
    "url": "https://drive.google.com/file/d/12iC_FpDcThL5V1kp9C6cFyrBj4iIIyb3/view"
  },
  {
    "title": "Gravitation",
    "rawName": "FR03 Gravitation.pdf",
    "subject": "physics",
    "path": "notes/physics/Gravitation/FR03 Gravitation.pdf",
    "size": "77.7 mb",
    "sizeBytes": 81454537,
    "date": "2026-10-02",
    "url": "https://drive.google.com/file/d/1MYUVXj1y3lpocLGYFhSkQqS31See8pzd/view"
  },
  {
    "title": "Thermodynamics",
    "rawName": "Thermodynamics.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Thermodynamics.pdf",
    "size": "24.0 mb",
    "sizeBytes": 25124134,
    "date": "2026-09-30",
    "url": "https://drive.google.com/file/d/1_pDyrH_64YlU_7aQDubj7MdAovbaFXPa/view"
  },
  {
    "title": "Sep 30, 2026 Young's Modulus",
    "rawName": "Sep 30, 2026 Young's Modulus",
    "subject": "recording",
    "path": "notes/physics/Mechanical Properties of Solids/Recordings /Sep 30, 2026 Young's Modulus",
    "size": "375.9 mb",
    "sizeBytes": 394176038,
    "date": "2026-09-30",
    "url": "https://drive.google.com/file/d/1e1ok3K0NslL_RKj4Hp9m4WjGWgrWWiOl/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-2 - 2026/09/30 12:30 IST",
    "rawName": "Mathematics \u00b7 Lecture-2 - 2026/09/30 12:30 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-30",
    "url": "https://drive.google.com/file/d/1K8oEibctddGoqchFBOAszBZwBM-zXLuc/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-5 - 2026/09/29 12:29 IST",
    "rawName": "Mathematics \u00b7 Lecture-5 - 2026/09/29 12:29 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-29",
    "url": "https://drive.google.com/file/d/1O7h7cpI4lPofgVpxh8l8NTS2tdftWzXv/view"
  },
  {
    "title": "Equilibrium",
    "rawName": "Equilibrium.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Equilibrium.pdf",
    "size": "5.3 mb",
    "sizeBytes": 5606423,
    "date": "2026-09-29",
    "url": "https://drive.google.com/file/d/1COFYE7yuPqOnsd8LfesvnwYhejIbJZKo/view"
  },
  {
    "title": "Sep 28, 2026 Keplar's Laws",
    "rawName": "Sep 28, 2026 Keplar's Laws",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 28, 2026 Keplar's Laws",
    "size": "412.0 mb",
    "sizeBytes": 431979563,
    "date": "2026-09-28",
    "url": "https://drive.google.com/file/d/1UnsZHeIoxHdAiyxqGetvZJSH8UyZSCMn/view"
  },
  {
    "title": "Chemistry \u00b7 Lecture-3 - 2026/09/28 12:29 IST",
    "rawName": "Chemistry \u00b7 Lecture-3 - 2026/09/28 12:29 IST",
    "subject": "recording",
    "path": "recordings/chemistry",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-28",
    "url": "https://drive.google.com/file/d/1EyL-4qaHAfQknMr7qrXMELV06lh9Q0jX/view"
  },
  {
    "title": "Chemistry \u00b7 Lecture-11 - 2026/09/26 10:14 IST",
    "rawName": "Chemistry \u00b7 Lecture-11 - 2026/09/26 10:14 IST",
    "subject": "recording",
    "path": "recordings/chemistry",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-26",
    "url": "https://drive.google.com/file/d/1BltYbXKgB4x0S8_gg88mj_RX5CzQKdDh/view"
  },
  {
    "title": "Sep 25, 2026 Escape speed, Motion of Satellites",
    "rawName": "Sep 25, 2026 Escape speed, Motion of Satellites",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 25, 2026 Escape speed, Motion of Satellites",
    "size": "369.3 mb",
    "sizeBytes": 387225479,
    "date": "2026-09-25",
    "url": "https://drive.google.com/file/d/1Qclcox3TgpXPsG4pB7thcfG0_Dh8uSAP/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-8 - 2026/09/25 10:27 IST",
    "rawName": "Mathematics \u00b7 Lecture-8 - 2026/09/25 10:27 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-25",
    "url": "https://drive.google.com/file/d/1L3IrCjfGT5kJcCVGED5_SOwk6EmMjk6w/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Gravitation/Target Discussion.pdf",
    "size": "186 kb",
    "sizeBytes": 190524,
    "date": "2026-09-24",
    "url": "https://drive.google.com/file/d/1_Ph22I7FkYDqeFvH7J_Uero2nmleEF2R/view"
  },
  {
    "title": "Sep 24, 2026 Gravitational Potential",
    "rawName": "Sep 24, 2026 Gravitational Potential ",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 24, 2026 Gravitational Potential ",
    "size": "296.7 mb",
    "sizeBytes": 311090919,
    "date": "2026-09-24",
    "url": "https://drive.google.com/file/d/1tM4mA6o7fB-r_JmO4obXUoVDgdkuZrq4/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-5 - 2026/09/24 10:28 IST",
    "rawName": "Mathematics \u00b7 Lecture-5 - 2026/09/24 10:28 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-24",
    "url": "https://drive.google.com/file/d/1g_nuCfaEQ-SJhFgrKIfU6-O-VNNqBs1M/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-4 - 2026/09/22 12:30 IST",
    "rawName": "Mathematics \u00b7 Lecture-4 - 2026/09/22 12:30 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-22",
    "url": "https://drive.google.com/file/d/1nHF2GWv8d2RMIm3H4tgd7MyNfF1MPQj_/view"
  },
  {
    "title": "Chemistry \u00b7 Lecture-2 - 2026/09/22 10:29 IST",
    "rawName": "Chemistry \u00b7 Lecture-2 - 2026/09/22 10:29 IST",
    "subject": "recording",
    "path": "recordings/chemistry",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-22",
    "url": "https://drive.google.com/file/d/1I_4F24EjgS_whf3sgOShVBiFRmPPCBRA/view"
  },
  {
    "title": "Sep 21, 2026 Field intensity, Gravitational P.E.",
    "rawName": "Sep 21, 2026 Field intensity, Gravitational P.E.",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 21, 2026 Field intensity, Gravitational P.E.",
    "size": "337.0 mb",
    "sizeBytes": 353393505,
    "date": "2026-09-21",
    "url": "https://drive.google.com/file/d/1jB1Nu-ZfXhYkBv6vW9yQktDDLbIxD36E/view"
  },
  {
    "title": "Chemistry \u00b7 Lecture-2 - 2026/09/21 12:29 IST",
    "rawName": "Chemistry \u00b7 Lecture-2 - 2026/09/21 12:29 IST",
    "subject": "recording",
    "path": "recordings/chemistry",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-21",
    "url": "https://drive.google.com/file/d/16tuWuXgym6S8KzLOrO3j2Ek8yxaho9_a/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/System of Particles and Rotational Motion/Target Discussion.pdf",
    "size": "26.1 mb",
    "sizeBytes": 27316271,
    "date": "2026-09-20",
    "url": "https://drive.google.com/file/d/1KVyB1tOnCDh7OkjyTDMKU0kra5qfHO-o/view"
  },
  {
    "title": "Redox Reaction",
    "rawName": "Redox Reaction.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Redox Reaction.pdf",
    "size": "11.4 mb",
    "sizeBytes": 11969266,
    "date": "2026-09-20",
    "url": "https://drive.google.com/file/d/1pUY9qcb0nCdD40f0V_JM_DDwCsHnyMl-/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-7 - 2026/09/19 12:14 IST",
    "rawName": "Mathematics \u00b7 Lecture-7 - 2026/09/19 12:14 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-19",
    "url": "https://drive.google.com/file/d/1E2CpBeQlnr4KY_sGHqLjDtXvj7nuvvSI/view"
  },
  {
    "title": "Chemistry \u00b7 Lecture-8 - 2026/09/19 10:10 IST",
    "rawName": "Chemistry \u00b7 Lecture-8 - 2026/09/19 10:10 IST",
    "subject": "recording",
    "path": "recordings/chemistry",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-19",
    "url": "https://drive.google.com/file/d/1tsMlWJJJTuHD15ReDCgGsNKnA3bpph5h/view"
  },
  {
    "title": "Sep 18, 2026 Acceleration due to Gravity",
    "rawName": "Sep 18, 2026 Acceleration due to Gravity",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 18, 2026 Acceleration due to Gravity",
    "size": "424.5 mb",
    "sizeBytes": 445082012,
    "date": "2026-09-18",
    "url": "https://drive.google.com/file/d/1kdpxDIog_okQYem9d7ddh6tXTYmDWsxw/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-5 - 2026/09/18 10:26 IST",
    "rawName": "Mathematics \u00b7 Lecture-5 - 2026/09/18 10:26 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-18",
    "url": "https://drive.google.com/file/d/1jaW7gBSVd_ZLp5FJKfUoeV2mu1bLV7QG/view"
  },
  {
    "title": "Sep 17, 2026 Newton's Law of Gravitation",
    "rawName": "Sep 17, 2026 Newton's Law of Gravitation ",
    "subject": "recording",
    "path": "notes/physics/Gravitation/Recordings /Sep 17, 2026 Newton's Law of Gravitation ",
    "size": "355.3 mb",
    "sizeBytes": 372579914,
    "date": "2026-09-17",
    "url": "https://drive.google.com/file/d/1u0PyVzTxRjP4gsgQWQwpLUlKVCZcL51r/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-3 - 2026/09/17 10:22 IST",
    "rawName": "Mathematics \u00b7 Lecture-3 - 2026/09/17 10:22 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-17",
    "url": "https://drive.google.com/file/d/1ItepgZ72gZbdiUagtt1Y33Tuq0wZ7QUW/view"
  },
  {
    "title": "Laws of Motion",
    "rawName": "FR03 Laws of Motion.pdf",
    "subject": "physics",
    "path": "notes/physics/Laws of Motion/FR03 Laws of Motion.pdf",
    "size": "139.4 mb",
    "sizeBytes": 146160940,
    "date": "2026-09-15",
    "url": "https://drive.google.com/file/d/1V7Y4AtGzqJI5l_fqp8JRvSOpQ9wGLUnA/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Work, Energy and Power/Target Discussion.pdf",
    "size": "22.2 mb",
    "sizeBytes": 23270229,
    "date": "2026-09-14",
    "url": "https://drive.google.com/file/d/1PS5EtkoYnVfvlvwAqZr2UZ7rV8mPhXFe/view"
  },
  {
    "title": "System of Particles and Rotational Motion",
    "rawName": "FR03 System of Particles and Rotational Motion.pdf",
    "subject": "physics",
    "path": "notes/physics/System of Particles and Rotational Motion/FR03 System of Particles and Rotational Motion.pdf",
    "size": "180.4 mb",
    "sizeBytes": 189180597,
    "date": "2026-09-14",
    "url": "https://drive.google.com/file/d/1mw2IQEGoNzI0lBMOcDp6BYrpWwrDg1Qh/view"
  },
  {
    "title": "Sep 14, 2026 Doubt Discussion (Work, Energy and Power)",
    "rawName": "Sep 14, 2026 Doubt Discussion (Work, Energy and Power)",
    "subject": "physics",
    "path": "notes/physics/Work, Energy and Power/Recording/Sep 14, 2026 Doubt Discussion (Work, Energy and Power)",
    "size": "537.4 mb",
    "sizeBytes": 563475902,
    "date": "2026-09-14",
    "url": "https://drive.google.com/file/d/16oq_oUaJHwYR-PSfJTq69EOUNJGnJJK4/view"
  },
  {
    "title": "Sep 11, 2026 Angular Impulse, Miscellaneous problems",
    "rawName": "Sep 11, 2026 Angular Impulse, Miscellaneous problems ",
    "subject": "recording",
    "path": "notes/physics/System of Particles and Rotational Motion/Recordings/Sep 11, 2026 Angular Impulse, Miscellaneous problems ",
    "size": "453.8 mb",
    "sizeBytes": 475834314,
    "date": "2026-09-11",
    "url": "https://drive.google.com/file/d/15vJR9h06A9tBRIHJv8pnuzkL-svJoeYK/view"
  },
  {
    "title": "Sep 10, 2026 Angular Momentum conservation",
    "rawName": "Sep 10, 2026 Angular Momentum conservation ",
    "subject": "recording",
    "path": "notes/physics/System of Particles and Rotational Motion/Recordings/Sep 10, 2026 Angular Momentum conservation ",
    "size": "361.7 mb",
    "sizeBytes": 379252226,
    "date": "2026-09-10",
    "url": "https://drive.google.com/file/d/1aTKI70q8jCGp4DUaFuwfy1_BT_hS4mUE/view"
  },
  {
    "title": "Mathematics \u00b7 Lecture-5 - 2026/09/10 10:22 IST",
    "rawName": "Mathematics \u00b7 Lecture-5 - 2026/09/10 10:22 IST",
    "subject": "recording",
    "path": "recordings/maths",
    "size": "stream",
    "sizeBytes": 0,
    "date": "2026-09-10",
    "url": "https://drive.google.com/file/d/14N_ZHuRkFPKLEnIGfn-o_YKl0BtbJU0Y/view"
  },
  {
    "title": "Sep 08, 2026 Angular Momentum",
    "rawName": "Sep 08, 2026 Angular Momentum",
    "subject": "recording",
    "path": "notes/physics/System of Particles and Rotational Motion/Recordings/Sep 08, 2026 Angular Momentum",
    "size": "413.4 mb",
    "sizeBytes": 433468479,
    "date": "2026-09-08",
    "url": "https://drive.google.com/file/d/15z5AVuAlkbHrzSyIJLaIT1SYyJEqTwgt/view"
  },
  {
    "title": "AIATS Test-1",
    "rawName": "AIATS Test-1.pdf",
    "subject": "physics",
    "path": "notes/physics/Test Discussion/AIATS Test-1.pdf",
    "size": "1.5 mb",
    "sizeBytes": 1585975,
    "date": "2026-09-04",
    "url": "https://drive.google.com/file/d/1FWT2lXxRjgIaYD6XXVaOqQxMOA0N6Iqa/view"
  },
  {
    "title": "Work, Energy and Power",
    "rawName": "FR03 Work, Energy and Power.pdf",
    "subject": "physics",
    "path": "notes/physics/Work, Energy and Power/FR03 Work, Energy and Power.pdf",
    "size": "135.6 mb",
    "sizeBytes": 142148035,
    "date": "2026-08-21",
    "url": "https://drive.google.com/file/d/11W_34D8ZfXaa5o7W8AW3tV24nCkS3ZC5/view"
  },
  {
    "title": "Mole Concept",
    "rawName": "Mole Concept.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole Concept.pdf",
    "size": "24.4 mb",
    "sizeBytes": 25591121,
    "date": "2026-08-11",
    "url": "https://drive.google.com/file/d/1QH4m1yY3j7UZp32Bp1YgTAzRx-nPOm-i/view"
  },
  {
    "title": "Step-3 Discussion",
    "rawName": "Step-3 Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Laws of Motion/Step-3 Discussion.pdf",
    "size": "11.1 mb",
    "sizeBytes": 11663532,
    "date": "2026-08-09",
    "url": "https://drive.google.com/file/d/1CdAx46jk2Yh50QPz4RRG_GaFZziJMmq7/view"
  },
  {
    "title": "Chemical Bonding",
    "rawName": "Chemical Bonding.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Chemical Bonding.pdf",
    "size": "37.5 mb",
    "sizeBytes": 39363253,
    "date": "2026-08-09",
    "url": "https://drive.google.com/file/d/16L439bJ0asjm2OHJvv6c0gc6iwOKJHs3/view"
  },
  {
    "title": "Gaseous State",
    "rawName": "Gaseous State.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Gaseous State.pdf",
    "size": "18.5 mb",
    "sizeBytes": 19362805,
    "date": "2026-08-05",
    "url": "https://drive.google.com/file/d/1sak8VhYJD1TE-nJ1DddtBVa4LsvLvDDy/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Laws of Motion/Target Discussion.pdf",
    "size": "37.8 mb",
    "sizeBytes": 39615498,
    "date": "2026-07-20",
    "url": "https://drive.google.com/file/d/1OBId7BFaskIxrvchEOBdsh46c92g3hDI/view"
  },
  {
    "title": "Motion in a Plane",
    "rawName": "FR03 Motion in a Plane.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Plane/FR03 Motion in a Plane.pdf",
    "size": "175.4 mb",
    "sizeBytes": 183916781,
    "date": "2026-07-06",
    "url": "https://drive.google.com/file/d/1mNNR-tIxGlrQhkVuKpMFAOa4VLEHjKQy/view"
  },
  {
    "title": "Step-3 Discussion",
    "rawName": "Step-3 Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Plane/Step-3 Discussion.pdf",
    "size": "27.8 mb",
    "sizeBytes": 29110317,
    "date": "2026-07-05",
    "url": "https://drive.google.com/file/d/1ANuOWn2yaC3V7DuJALpSro9WchVyGxQF/view"
  },
  {
    "title": "Periodic Classification",
    "rawName": "Periodic Classification.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Periodic Classification.pdf",
    "size": "15.1 mb",
    "sizeBytes": 15869379,
    "date": "2026-06-27",
    "url": "https://drive.google.com/file/d/1KGjV7HVco3ey9JpUwSrtYTdxeTsKpTVL/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Plane/Target Discussion.pdf",
    "size": "33.6 mb",
    "sizeBytes": 35266164,
    "date": "2026-06-26",
    "url": "https://drive.google.com/file/d/1RwZ-c1g3oG2vRFn40cwvjUv9rPAnOy9W/view"
  },
  {
    "title": "atomic structure answer key",
    "rawName": "atomic structure answer key.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/atomic structure answer key.pdf",
    "size": "186 kb",
    "sizeBytes": 191470,
    "date": "2026-06-18",
    "url": "https://drive.google.com/file/d/1zCiD8nQvm9-BVLNGYy7X3i1n_kluKnu-/view"
  },
  {
    "title": "Step-3 Discussion",
    "rawName": "Step-3 Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Straight Line/Step-3 Discussion.pdf",
    "size": "27.2 mb",
    "sizeBytes": 28495040,
    "date": "2026-06-16",
    "url": "https://drive.google.com/file/d/1gzMAE4ZcriXzzOxp8YuhV4CTqCHMQqS7/view"
  },
  {
    "title": "Practise Test- June 10",
    "rawName": "Practise Test- June 10.pdf",
    "subject": "physics",
    "path": "notes/physics/Test Discussion/Practise Test- June 10.pdf",
    "size": "8.0 mb",
    "sizeBytes": 8396837,
    "date": "2026-06-12",
    "url": "https://drive.google.com/file/d/1Kp5vs-DMwwXd8GfQ9Hp2HmldMuzWpsLZ/view"
  },
  {
    "title": "ATOMIC STRUCTURE",
    "rawName": "ATOMIC STRUCTURE.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/ATOMIC STRUCTURE.pdf",
    "size": "23.8 mb",
    "sizeBytes": 24985219,
    "date": "2026-06-06",
    "url": "https://drive.google.com/file/d/11MAK8CcJrO-nBtWjWRrfbqVcsWj56pB0/view"
  },
  {
    "title": "Worksheet Final - Atomic Structure",
    "rawName": "Worksheet Final - Atomic Structure.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Worksheet Final - Atomic Structure.pdf",
    "size": "2.7 mb",
    "sizeBytes": 2789568,
    "date": "2026-06-03",
    "url": "https://drive.google.com/file/d/1POTO18hKU9wCRdJ55T0rV5uksle8zPl4/view"
  },
  {
    "title": "Motion in a Straight Line",
    "rawName": "FR03 Motion in a Straight Line.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Straight Line/FR03 Motion in a Straight Line.pdf",
    "size": "106.8 mb",
    "sizeBytes": 112024308,
    "date": "2026-06-01",
    "url": "https://drive.google.com/file/d/1w2YbmfTCgH9YwwRAkL_ItdvgygKbbxic/view"
  },
  {
    "title": "Units and Measurements",
    "rawName": "FR03 Units and Measurements.pdf",
    "subject": "physics",
    "path": "notes/physics/Units and Measurements/FR03 Units and Measurements.pdf",
    "size": "57.9 mb",
    "sizeBytes": 60757701,
    "date": "2026-05-31",
    "url": "https://drive.google.com/file/d/1Z7bFAbExtZMQ9dWT1zVcqkjRoXnBfF0R/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Motion in a Straight Line/Target Discussion.pdf",
    "size": "40.7 mb",
    "sizeBytes": 42655052,
    "date": "2026-05-26",
    "url": "https://drive.google.com/file/d/1AlTcN8DSS5wAdo0LQ100Phh3moX4XL-O/view"
  },
  {
    "title": "Target Discussion",
    "rawName": "Target Discussion.pdf",
    "subject": "physics",
    "path": "notes/physics/Units and Measurements/Target Discussion.pdf",
    "size": "25.0 mb",
    "sizeBytes": 26236356,
    "date": "2026-05-26",
    "url": "https://drive.google.com/file/d/12G7QuV1Ntu3-k37eV4ut8GQn52vavpJq/view"
  },
  {
    "title": "Test Atomic Structure",
    "rawName": "Test Atomic Structure.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Test Atomic Structure.pdf",
    "size": "1.9 mb",
    "sizeBytes": 2031220,
    "date": "2026-05-19",
    "url": "https://drive.google.com/file/d/17cvFVQXTIEctab2xg8T1SRjvdccMIWvF/view"
  },
  {
    "title": "Mole Concept Final answer key",
    "rawName": "Mole Concept Final answer key .pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Mole Concept Final answer key .pdf",
    "size": "2.0 mb",
    "sizeBytes": 2121084,
    "date": "2026-05-15",
    "url": "https://drive.google.com/file/d/12ocL91ED-_BSsM_zhVE4vnhmawLy8ffb/view"
  },
  {
    "title": "Mole Concept Final Assignment Solutions",
    "rawName": "Mole Concept Final Assignment Solutions .pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Mole Concept Final Assignment Solutions .pdf",
    "size": "8.9 mb",
    "sizeBytes": 9318482,
    "date": "2026-05-14",
    "url": "https://drive.google.com/file/d/1Zu4Urk6bGc6EJ4LhoV23RMp0vNgVX84u/view"
  },
  {
    "title": "ATOMIC STRUCTURE",
    "rawName": "ATOMIC STRUCTURE.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/ATOMIC STRUCTURE.pdf",
    "size": "20.7 mb",
    "sizeBytes": 21661871,
    "date": "2026-05-14",
    "url": "https://drive.google.com/file/d/1Gm10Wvu4_EXzfYbl1agjmM_aHytHUq0i/view"
  },
  {
    "title": "Mole Concept Final",
    "rawName": "Mole Concept Final.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Mole Concept Final.pdf",
    "size": "8.8 mb",
    "sizeBytes": 9213011,
    "date": "2026-05-07",
    "url": "https://drive.google.com/file/d/1nV4dAs4rupL553DhWdYXNa6ntAIFVDiv/view"
  },
  {
    "title": "Integrals (basic)",
    "rawName": "Integrals (basic).pdf",
    "subject": "physics",
    "path": "notes/physics/Integrals (basic).pdf",
    "size": "141 kb",
    "sizeBytes": 145068,
    "date": "2026-05-07",
    "url": "https://drive.google.com/file/d/1C-jVCeduKJGesCAn-VkOvibiPcybOvoS/view"
  },
  {
    "title": "Basic Mathematics",
    "rawName": "FR03 Basic Mathematics.pdf",
    "subject": "physics",
    "path": "notes/physics/Basic Mathematics/FR03 Basic Mathematics.pdf",
    "size": "56.8 mb",
    "sizeBytes": 59532227,
    "date": "2026-05-06",
    "url": "https://drive.google.com/file/d/1vEux5JdhuNLAmaRM4EEMNXOvBOd8I-zV/view"
  },
  {
    "title": "Mole Concept",
    "rawName": "Mole Concept.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Mole Concept.pdf",
    "size": "24.4 mb",
    "sizeBytes": 25583042,
    "date": "2026-05-03",
    "url": "https://drive.google.com/file/d/1fwqacMYWbSIIhYF46OWUCaV2FhRvRGvH/view"
  },
  {
    "title": "DPP Answer Key 6-8",
    "rawName": " DPP Answer Key 6-8.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/ DPP Answer Key 6-8.pdf",
    "size": "167 kb",
    "sizeBytes": 171332,
    "date": "2026-04-27",
    "url": "https://drive.google.com/file/d/1yF7T7zBIf-DqBStsIzi5bHtt1N8XggvM/view"
  },
  {
    "title": "Derivative (Basic) - 2",
    "rawName": "Derivative (Basic) - 2.pdf",
    "subject": "physics",
    "path": "notes/physics/Derivative (Basic) - 2.pdf",
    "size": "607 kb",
    "sizeBytes": 622173,
    "date": "2026-04-20",
    "url": "https://drive.google.com/file/d/1l4Yf2BBCZQp9spTFes6jZhEh_gWBxEC2/view"
  },
  {
    "title": "Derivative (Basic)",
    "rawName": "Derivative (Basic).pdf",
    "subject": "physics",
    "path": "notes/physics/Derivative (Basic).pdf",
    "size": "267 kb",
    "sizeBytes": 274209,
    "date": "2026-04-20",
    "url": "https://drive.google.com/file/d/1c5sPGqT74jorzHuIRhzKdUgIP9EOUCeQ/view"
  },
  {
    "title": "Application of derivatives (basic)",
    "rawName": "Application of derivatives (basic).pdf",
    "subject": "physics",
    "path": "notes/physics/Application of derivatives (basic).pdf",
    "size": "85 kb",
    "sizeBytes": 87719,
    "date": "2026-04-20",
    "url": "https://drive.google.com/file/d/1g8kvvjakpBBGjH4lPNnIRxo72q2Ld6FD/view"
  },
  {
    "title": "Mole Concept-DPP FR-01",
    "rawName": "Mole Concept-DPP FR-01.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Mole Concept-DPP FR-01.pdf",
    "size": "2.0 mb",
    "sizeBytes": 2147811,
    "date": "2026-04-15",
    "url": "https://drive.google.com/file/d/1LYiLFlw1Y8PB5wggMOYhyc2Dgs0JyIKN/view"
  },
  {
    "title": "Dpp Answer Key",
    "rawName": "Dpp Answer Key.pdf",
    "subject": "chemistry",
    "path": "notes/chemistry/Mole concept/Dpp Answer Key.pdf",
    "size": "222 kb",
    "sizeBytes": 227817,
    "date": "2026-04-07",
    "url": "https://drive.google.com/file/d/1WArF3WDWMaMqVEoWZosN-mUKxcAU8CKX/view"
  }
];
